name: Provision of Ec2 instance and configuration with Ansible

on:
  push:
    branches:
      - main

jobs:
  Provision_ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name : setup python 3.x 
        uses : actions/setup-python@v2
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible boto3
          ansible-galaxy collection install amazon.aws

      - name : configuration of aws secret
        uses : aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name : create a pem file
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/ubuntu.pem
          chmod 600 ~/.ssh/ubuntu.pem 
      
      - name : debug 
        run: ls -l ~/.ssh/ubuntu.pem